<h1>Splošni pogoji uporabe storitev</h1><hr />

<p>PROSIMO, POZORNO PREBERITE POGODBO O UPORABI WIFIS (»POGODBA«), PREDEN SE PRIJAVITE ZA WIFIS RAČUN OZ. PREDEN UPORABITE WIFIS STORITVE ZA OBRAČUNAVANJE IN OVERJANJE. TA POGODBA PRAVNO ZAVEZUJE VAS (SUBJEKT ALI OSEBA) IN HOTSPOT SYSTEM LDT. KO USTVARITE RAČUN IN/ALI UPORABLJATE STORITEV WIFIS WIRELESS, SE ZAVEZUJETE K NASLEDNJIM POGOJEM IN DOLOČILOM. ČE SE NE STRINJATE Z VSEMI POGOJI IN DOLOČILI V TEJ POGODBI, NE SMETE USTVARITI RAČUNA ALI UPORABLJATI TE STORITVE.</p>

<h2>POGODBA O UPORABI</h2>
<p>Pogoji in določila te pogodbe urejajo razmerje med vami (»uporabnik« ali »vi«) in WIFIS WIRELESS (»WIFIS«). WIFIS ponuja uporabnikom, ki so ustvarili račun, svoje storitve za overjanje in obračunavanje (izbirno), kot lahko občasno obstajajo (»storitve«). Ko ustvarite ali uporabljate račun WIFIS, ste vezani na to pogodbo in se zavezujete, da boste storitve uporabljali v skladu s to pogodbo in drugimi pravili WIFIS, objavljenimi na spletni strani WIFIS.</p>

<h2>1. PLAČILNE OBVEZNOSTI.</h2>
<p>WIFIS morate (i) posredovati natančne in popolne osebne podatke, vključno z uradnim imenom, naslovom in telefonsko številko, in (ii) sporočiti vse spremembe teh podatkov v 30 dneh od nastanka spremembe. Odgovorni ste za vse bremenitve na vašem računu. Če imate vprašanja v zvezi z bremenitvami računa, kontaktirajte WIFIS službo za pomoč strankam (podrobnosti najdete na spletni strani). Vse bremenitve so veljavne, razen če se pritožite v 45 dneh od datuma obračuna. Bremenitve, ki so starejše od 45 dni, se ne spreminjajo.</p>

<p>Bremenitve se na vaše kreditne kartice obračunajo prek plačilnega posrednika PAYPAL, v imenu dostopne točke ali omogočene lokacije. Računi se lahko dobijo na dostopni točki ali omogočeni lokaciji. WIFIS ne zapisuje ali shranjuje podatkov o vaši kreditni kartici in obračunavanju. WIFIS ni odgovoren za bremenitve ali stroške (npr. negativno stanje na računu, presežen limit na kartici itd.), ki so posledica bremenitev, opravljenih prek plačilnega posrednika. Sporne račune lahko WIFIS zamrzne ali ukine po lastni presoji. Toda bremenitve se lahko nadaljujejo, dokler ni račun ukinjen, in se lahko dodajo pavšal, zamudna nadomestila in druge podobne pristojbine.</p>

<h2>2. LOKACIJE IN PRISTOJBINE.</h2>
<p>Dostopne točke ali omogočene lokacije morda niso na voljo na vseh območjih. Storitve imajo lahko na različnih lokacijah različne cene; nekatere lokacije niso vključene v tekoče naročnine WIFIS ali druge pavšalne načrte. Trenutne cene se po lokacijah razlikujejo. Če niste prepričani glede zaračunanih pristojbin na določeni lokaciji, ki ponuja storitev, morate kontaktirati WIFIS. Sami ste odgovorni za določanje pristojbin, vsakič preden uporabite storitev.</p>

<h2>3. VAŠE UPORABNIŠKO IME IN GESLO; VARNOST.</h2>
<p>Ob registraciji boste izbrali ali prejeli uporabniško ime in geslo. Vi ste edini pooblaščeni uporabnik vašega WIFIS računa, razen če vaš načrt storitve izrecno ne določa drugače, in vaša uporaba tega računa mora biti v skladu s to pogodbo. Vaše geslo naj bo zaupno, kar preprečuje, da bi kdo drug uporabljal storitve prek vašega računa. Ko ugotovite nepooblaščeno rabo vašega računa, o tem nemudoma obvestite WIFIS. Na HotSpot se z istim uporabniškim imenom ne morete prijaviti istočasno z več različnih naprav. Na nekaterih lokacijah si lahko sistem zapomni napravo, s katero ste se prvič prijavili v sistem, in blokira povezavo s katerekoli druge naprave, tudi če ste se s prvotno napravo tudi odjavili s HotSpota. Strinjate se, da ne boste uporabljali avtomatičnih metod, s čimer bi se želeli izogniti prekinitvi povezave zaradi neaktivnosti; povezave morda ne boste mogli ohraniti, če je ne boste aktivno uporabljali. Prav tako se strinjate, da ne boste ponujali storitev javnega obveščanja prek brezžičnega lokalnega omrežja.</p>

<p>Uporabniška imena in gesla so last WIFIS in WIFIS jih lahko kadarkoli spremeni ali zamenja.</p>

<h2>4. NADZOROVANJE STORITEV.</h2>
<p>WIFIS ni treba nadzorovati storitev, a lahko to vseeno stori in razkrije podatke v zvezi z uporabo storitev iz kateregakoli razloga, če WIFIS po lastni presoji oceni, da je to upravičeno, na primer, da se zadosti zakonom, predpisom ali vladnim ali pravnim zahtevam; pravilno upravlja s storitvami; ali zaščiti sebe in svoje uporabnike.</p>

<h2>5. OMEJITEV ODGOVORNOSTI GLEDE JAMSTVA.</h2>
<p>RAZEN DOLOČENIH IZDELKOV IN STORITEV, KI SO IZRECNO NAVEDENI KOT DEL PONUDBE WIFIS, WIFIS NIMA VPLIVA NAD VSEBINAMI, PODATKI, IZDELKI ALI STORITVAMI NA INTERNETU. INTERNET VSEBUJE NEUREJENE VSEBINE, NEKATERE OD NJIH TUDI JASNO PRIKAZUJEJO SPOLNOST ALI SO LAHKO ZA VAS ŽALJIVE. WIFIS NIMA NADZORA NAD TAKIMI VSEBINAMI IN ZANJE NE SPREJEMA ODGOVORNOSTI. SAMI PREVZEMATE POLNO ODGOVORNOST IN TVEGANJE PRI UPORABI STORITEV IN INTERNETA IN STE IZKLJUČNO ODGOVORNI ZA PRESOJO NATANČNOSTI, POPOLNOSTI IN KORISTNOSTI VSEH STORITEV, IZDELKOV IN DRUGIH PODATKOV IN KAKOVOSTI TER PRIMERNOSTI ZA PRODAJO VSEGA BLAGA, KI JE NA VOLJO PREK STORITVE ALI INTERNETA.</p>

<h2>6. OMEJITEV ODGOVORNOSTI.</h2>
<p>STORITVE SO NA VOLJO PO NAČELU »TAKE KOT SO« IN »KOT SO NA RAZPOLAGO«. WIFIS NE JAMČI, DA BO STORITEV NEPREKINJENA, BREZ NAPAK IN BREZ VIRUSOV ALI DRUGIH ŠKODLJIVIH ELEMENTOV. WIFIS NE DAJE IZRECNIH, NAZNAČENIH ALI ZAKONSKIH JAMSTEV IN UPORABNIK SE ODPOVEDUJE VSEM JAMSTVOM, VKLJUČNO VENDAR NE OMEJENO NA JAMSTVO UPRAVIČENOSTI, NEKRŠITVE, PRIMERNOSTI ZA PRODAJO IN PRIMERNOSTI ZA DOLOČEN NAMEN V ZVEZI S KATERIMKOLI BLAGOM, PODATKI ALI STORITVIJO, KI JIH NEPOSREDNO ALI POSREDNO PONUJA WIFIS. IZRECNO PRIZNAVATE, DA SO V BREZŽIČNIH KOMUNIKACIJAH IN TEHNOLOGIJI VGRAJENA TVEGANJA VARNOSTI, ZASEBNOSTI IN ZAUPNOSTI IN WIFIS NE DAJE NOBENIH ZAGOTOVIL ALI JAMSTEV V ZVEZI S TAKIMI TVEGANJI. NOBENI NASVETI ALI INFORMACIJE, KI JIH PREJMETE OD WIFIS ALI NJEGOVIH PREDSTAVNIKOV, NE PREDSTAVLJAJO JAMSTVA. WIFIS IN NJEGOVI ZAPOSLENI NISO ODGOVORNI ZA KAKRŠNEKOLI STROŠKE ALI ODŠKODNINE, KI IZHAJAJO NEPOSREDNO ALI POSREDNO IZ VAŠE UPORABE STORITEV ALI INTERNETA, VKLJUČNO S POSREDNIMI, NAKLJUČNIMI, ODVRAČILNIMI, VEČKRATNIMI, POSEBNIMI, KAZNOVALNIMI ALI POSLEDIČNIMI ODŠKODNINAMI. V VSAKEM PRIMERU KUMULATIVNA ODGOVORNOST WIFIS DO KATEREGAKOLI UPORABNIKA ZA VSE ZAHTEVKE V ZVEZI Z UPORABO STORITEV IN/ALI LICENČNIH PROGRAMOV NE BO PRESEGLA SKUPNEGA ZNESKA, KI JE BIL PLAČAN ZA STORITVE V OBDOBJU ENEGA LETA PRED ČASOM NASTANKA TERJATVE.</p>

<h2>7. PLAČILO ODŠKODNIN.</h2>
<p>Strinjate se, da boste na lastne stroške WIFIS, njegove podružnice, direktorje in zaposlene oprostili obveznosti za vse stroške, zahtevke in razumne odvetniške honorarje, ki izhajajo iz kakršnekoli trditve, da je vaša uporaba storitev škodovala ali kako drugače kršila kakršnokoli pravico tretje osebe ali kršila kakšen zakon. </p>

<h2>8. PRAVILNIK O SPREJEMLJIVI RABI.</h2>
<p>Vsi uporabniki storitev in spletne strani WIFIS in/ali programske opreme WIFIS se strinjajo in morajo ravnati v skladu z 8. točko, ki vsebuje pravilnik o sprejemljivi rabi WIFIS, in vaša uporaba storitev, spletne strani ali programske opreme, ki jo ponuja WIFIS, pomeni, da se zavezujete, da boste spoštovali določila tega pravilnika. Ta pravilnik je namenjen izboljšanju uporabe interneta, s tem, da preprečuje nesprejemljive načine rabe. WIFIS ne uporablja aktiven nadzor uporabe storitev v normalnih okvirih. Podobno WIFIS tudi ne izvaja uredniškega nadzora ali pregleda nad vsebino katerekoli spletne strani, elektronskega prenosa pošte, skupine za razprave ali drugih vsebin, ki so bile ustvarjene ali so dostopne prek naših storitev. Toda WIFIS lahko odstrani, blokira ali drugače omeji vsebine, ki so po lastni presoji WIFIS nezakonite, izpostavijo WIFIS odgovornosti ali kršijo ta pravilnik. WIFIS lahko sodeluje s pravnimi organi in/ali tretjimi osebami pri preiskovanju domnevnih zločinov ali civilnopravnih kršitev. Kršenje tega pravilnika lahko vodi v začasno izključitev ali ukinitev dostopa do storitve in/ali WIFIS računa ali drugih ukrepov, ki so navedeni spodaj. Ko uporabnik uporablja storitve, je tretja oseba, od katere je WIFIS pridobil pravico do dostopa do HotSpota, na katerem se uporabljajo storitve, predvideni upravičenec tega pravilnika.</p> 

<p>Brez omejevanja navedenega se strinjate, da storitev ne boste uporabljali za: </p>
<p>(i) širjenje vsebin (s prenosom, objavljanjem, prek e-pošte ali kako drugače), ki so nezakonite, grozilne, nasilne, napadalne, deliktne, klevetniške, vulgarne ali napadalne do zasebnosti drugih, sovražne ali rasno, etnično ali drugače nestrpne; </p>
<p>(ii) škodovanje ali poskus škodovanja mladoletnim osebam na kakršenkoli način; </p>
<p>(iii) izdajanje za katerokoli osebo ali subjekt ali lažno navajanje ali drugačno zavajanje vaše povezave z osebo ali subjektom; ponarejanje glav ali drugačno manipuliranje z označbami, z namenom, da prikrijete izvor katerekoli vsebine, ki se prenaša prek storitev; </p>
<p>(iv) širjenje vsebin (s prenosom, objavljanjem, prek e-pošte ali kako drugače), ki jih po nobenem zakonu ali pogodbenem ali upraviteljskem dogovoru nimate pravice širiti (npr. notranje informacije, informacije z lastninsko pravico in zaupne informacije, ki ste jih pridobili oz. so vam bile razkrite kot del delovnega razmerja ali prek sporazuma o nerazkrivanju podatkov); </p>
<p>(v) širjenje vsebin (s prenosom, objavljanjem, prek e-pošte ali kako drugače), ki kršijo katerikoli patent, blagovno znamko, poslovno skrivnost, avtorsko pravico ali druge lastniške pravice katerekoli osebe; </p>
<p>(vi) širjenje (s prenosom, objavljanjem, prek e-pošte ali kako drugače) nezaželenih ali nedovoljenih reklam, reklamnih materialov, »vsiljene pošte«, »spama«, »verižnih pisem«, »piramidnih iger« in vseh drugih vrst akviziterske prodaje; </p>
<p>(vii) širjenje vsebin (s prenosom, objavljanjem, prek e-pošte ali kako drugače), ki vsebujejo viruse ali druge vrste računalniške kode, datotek ali programov, ki so zasnovani tako, da prekinejo, uničijo ali omejijo funkcionalnost programske ali strojne opreme računalnika ali telekomunikacijske opreme; </p>
<p>(viii) motenje normalnega poteka dialoga, povzročitev prehitrega premikanja zaslona in posledično oviranje tipkanja drugih uporabnikov, ali kakršnokoli drugo obnašanje, ki negativno vpliva na interakcijo drugih uporabnikov v realnem času; </p>
<p>(ix) motenje ali prekinitev storitve ali strežnikov ali omrežij, ki so vezani na storitev, ali neupoštevanje pogojev, postopkov, pravil ali določil omrežij, ki so vezana na storitev; </p>
<p>(x) namerno ali nenamerno kršenje veljavnih lokalnih, območnih, državnih ali mednarodnih zakonov, vključno vendar ne omejeno na določila Komisije za vrednostne papirje in borzo Združenih držav Amerike, vsakršna določila katerekoli nacionalne ali druge bonitetne agencije, vključno z borzo v New Yorku, ameriško borzo ali NASDAQ-om in vsakršnimi določili, ki imajo zakonsko moč; </p>
<p>(xi) »zalezovanje« ali drug način nadlegovanja druge osebe; ali zbiranje oz. shranjevanje ali poskus zbiranja oz. shranjevanja osebnih podatkov tretjih oseb, brez njihovega vedenja ali dovoljenja; </p>
<p>(xii) preprodajanje storitev brez dovoljenja WIFIS; </p>
<p>(xiii) prenos velike količine podatkov, še posebej neprekinjen prenos velike količine podatkov, spletno gostovanje spletnega strežnika, IRC strežnika ali kateregakoli drugega strežnika. </p>

<p>WIFIS prosi, da nam kdorkoli, ki sumi, da prihaja do kršitve tega pravilnika, to nemudoma sporoči. Če je možno, nam posredujte naslednje podatke: (i) IP-naslov domnevnega kršitelja; (ii) datum in uro domnevne kršitve (vključno s časovnim pasom); in (iii) dokaze o domnevni kršitvi. Ko pišete pritožbo zoper nezaželeno pošto, prosimo, priložite kopijo e-poštnega sporočila s celotnimi glavami, ki nam navadno razkrijejo vse zgoraj navedene podatke. Druge situacije bodo zahtevale drugačne načine posredovanja potrebnih podatkov. </p>

<p>WIFIS se lahko kot odgovor na pritožbe po lastni presoji zateče k enemu ali več od naslednjih ukrepov, ali ukrepov, ki niso navedeni: (i) izrekanje pisnih in ustnih opozoril; (ii) zamrznitev uporabniškega računa; (iii) ukinitev uporabniškega računa; (iv) izdaja računa za administrativne stroške in/ali bremenitve za ponovno aktivacijo računa z minimalnimi administrativnimi stroški; ali (v) pravno ukrepanje za odreditev kršitev in/ali za pobiranje morebitnih odškodnin, ki izhajajo iz kršitev. </p>

<h2>9. TRAJANJE POGODBE.</h2>
<p>Stalna raba storitev pomeni, da sprejemate to pogodbo in vse njene nadaljnje različice. Če ste nezadovoljni s storitvami ali z njimi povezanimi pogoji, določili, pravili, politiko, smernicami ali praksami, je vaš edini možen ukrep prenehanje rabe storitev in zaprtje vašega računa. </p>

<h2>10. AVTORSKE PRAVICE IN BLAGOVNE ZNAMKE.</h2>
<p>Vsa vsebina na spletni strani WIFIS, vključno vendar ne omejeno na besedila grafike, logotipe, gumbe, ikone, slike in programsko opremo, je v lasti WIFIS ali njegovih dajalcev licence ali partnerjev. Razmnoževanje, kopiranje, spreminjanje, distribucija, širjenje, posnemanje, razkazovanje ali izvajanje vsebin spletnih strani WIFIS je brez izrecnega pisnega dovoljenja s strani WIFIS strogo prepovedano.</p>

<h2>11. UKINITEV NAROČNINE.</h2>
<p>Vaš račun lahko kadarkoli in zaradi kateregakoli razloga ukinete tako, da na WIFIS pošljete obvestilo o nameri po ukinitvi vsaj 5 delovnih dni pred koncem vašega obračunskega obdobja. Ukinitev bo končana šele, ko od WIFIS dobite številko o potrditvi ukinitve. Če obvestilo o nameri po ukinitvi prejmemo vsaj 5 delovnih dni pred zaključkom vašega obračunskega obdobja, bo vaš račun ukinjen na koncu vašega tekočega obračunskega obdobja. Če obvestilo o nameri po ukinitvi prejmemo manj kot 5 delovnih dni pred zaključkom vašega obračunskega obdobja, se lahko bremenitve nadaljujejo do konca naslednjega obračunskega obdobja. </p>

<p>WIFIS lahko po lastni presoji brez predhodnega obvestila prekliče to pogodbo, vaše geslo, račun ali vašo uporabo storitev iz kateregakoli razloga, vključno v primerih, ko sumi, da ste kršili to pogodbo ali katerakoli druga določila, ki veljajo za uporabnike, ali če do določenega roka niste poravnali vaših finančnih obveznosti. WIFIS vam lahko obvestilo o ukinitvi pošlje po e-pošti, navadni pošti ali kurirski službi na naslov, ki ste ga navedli za storitve. Vsa obvestila bodo začela veljati na prvi (1.) koledarski dan po datumu pošiljanja prek elektronske pošte ali četrti (4.) koledarski dan po datumu pošiljanja pošte prvega razreda ali predaje pri komercialni kurirski službi.</p>

<p>Določila naslednjih členov te pogodbe veljajo tudi v primeru njene prekinitve: 3, 5, 6, 7, 8, 10 in 11.</p>