<h1>Terms of service</h1><hr />

<p>PLEASE READ THE FOLLOWING WIFIS USER AGREEMENT (THE "AGREEMENT") CAREFULLY BEFORE SIGNING UP FOR A WIFIS ACCOUNT OR USING THE WIFIS BILLING AND AUTHENTICATION SERVICES. THIS AGREEMENT IS A LEGALLY BINDING AGREEMENT BETWEEN YOU (AN ENTITY OR PERSON) AND WIFIS WIRELESS. BY PROCEEDING TO ESTABLISH AN ACCOUNT AND/OR USE THE WIFIS WIRELESS SERVICE, YOU AGREE TO BE BOUND TO THE TERMS AND CONDITIONS STATED BELOW. IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, YOU MUST NOT SIGN UP FOR AN ACCOUNT OR USE THE SERVICE.</p>

<h2>USER AGREEMENT</h2>

<p>The terms and conditions of this Agreement govern the relationship between you ("User" or "you") and WIFIS WIRELESS ("WIFIS"). WIFIS provides its authentication and billing services (optional), as they may exist from time to time ("Services"), to Users who establish an account. By establishing or using an account with WIFIS, you agree to be bound by this Agreement and to use the Services in compliance with this Agreement and other WIFIS policies posted on the WIFIS website.</p>

<h2>1. PAYMENT OBLIGATIONS.</h2>
<p>You must (i) provide WIFIS with accurate and complete personal information including legal name, address, telephone number and (ii) report to WIFIS all changes to this information within 30 days of the change. You are responsible for any charges to your account. If you have questions regarding charges to an account, you should contact WIFIS's Help Desk (see website for details). All charges are considered valid unless disputed in writing within 45 days of the billing date. Adjustments will not be made for charges that are more than 45 days old.</p>

<p>Charges are billed to your credit cards by PAYPAL, on behalf of the access point or enabled venue. Invoices can be obtained from the access point or enabled venue. WIFIS does not record or store your credit card and billing information. WIFIS is not responsible for any charges or expenses (e.g., for overdrawn accounts, exceeding credit card limits, etc.) resulting from charges billed by the 3rd party merchant processor. Delinquent accounts may be suspended or canceled at WIFIS's sole discretion. However, charges may continue to accrue until the account is canceled and collection, and late fees or other similar fees may be added.</p>

<h2>2. LOCATIONS AND FEES.</h2>
<p>Access points or enabled venues may not be available in all areas. The Services may entail different fees at different locations; some locations are not included in WIFIS's on-going subscription accounts or other flat-rate plans. Current prices for vary by locations. You must contact WIFIS if you are unsure of the fees charged at a particular location where the Services are available. You are responsible for determining the fees prior to using the Services each time.</p>

<h2>3. YOUR USERNAME AND PASSWORD; SECURITY.</h2>
<p>Upon registration, you will select or receive a username and password. You are the only authorized user of your WIFIS account, unless expressly specified otherwise in your service plan, and your use of your account must comply with this Agreement. You should keep your password confidential so that no one else may access the Services through your account. Please notify WIFIS immediately upon discovering any unauthorized use of your account. You are not allowed to log in to a hotspot using the same username from multiple devices simultaneously. In some locations the system may record your device which you use to log in to the system at the first time and may block the connection from any other devices, even if you log out from the hotspot with that device. You agree not to use any automatic method to avoid disconnection due to inactivity; you may not maintain a connection unless actively using it. You also agree not to provide any public information services over a wireless LAN connection. </p>

<p>Usernames and passwords are WIFIS's property and WIFIS may alter or replace them at any time. </p>

<h2>4. MONITORING THE SERVICES.</h2>
<p>WIFIS has no obligation to monitor the Services, but may do so and disclose information regarding use of the Services for any reason if WIFIS, in its sole discretion, believes that it is reasonable to do so, including to satisfy laws, regulations, or governmental or legal requests; operate the Services properly; or protect itself and its Users.</p>

<h2>5. WARRANTY DISCLAIMER.</h2>
<p>EXCEPT FOR CERTAIN PRODUCTS AND SERVICES SPECIFICALLY IDENTIFIED AS BEING OFFERED BY WIFIS, WIFIS DOES NOT CONTROL ANY MATERIALS, INFORMATION, PRODUCTS, OR SERVICES ON THE INTERNET. THE INTERNET CONTAINS UNEDITED MATERIALS, SOME OF WHICH ARE SEXUALLY EXPLICIT OR MAY BE OFFENSIVE TO YOU. WIFIS HAS NO CONTROL OVER AND ACCEPTS NO RESPONSIBILITY FOR SUCH MATERIALS. YOU ASSUME FULL RESPONSIBILITY AND RISK FOR USE OF THE SERVICES AND THE INTERNET AND ARE SOLELY RESPONSIBLE FOR EVALUATING THE ACCURACY, COMPLETENESS, AND USEFULNESS OF ALL SERVICES, PRODUCTS, AND OTHER INFORMATION, AND THE QUALITY AND MERCHANTABILITY OF ALL MERCHANDISE PROVIDED THROUGH THE SERVICE OR THE INTERNET.</p>

<h2>6. LIMITATION OF LIABILITY.</h2>
<p>THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WIFIS DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WIFIS MAKES NO WARRANTIES, EXPRESS, IMPLIED OR STATUTORY, AND USER WAIVES ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE, NONINFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE REGARDING ANY MERCHANDISE, INFORMATION OR SERVICE PROVIDED BY OR THROUGH WIFIS DIRECTLY OR INDIRECTLY. YOU EXPRESSLY ACKNOWLEDGE THAT THERE ARE SECURITY, PRIVACY AND CONFIDENTIALITY RISKS INHERENT IN WIRELESS COMMUNICATIONS AND TECHNOLOGY AND WIFIS DOES NOT MAKE ANY ASSURANCES OR WARRANTIES RELATING TO SUCH RISKS. NO ADVICE OR INFORMATION GIVEN BY WIFIS OR ITS REPRESENTATIVES WILL CREATE A WARRANTY. WIFIS AND ITS EMPLOYEES ARE NOT LIABLE FOR ANY COSTS OR DAMAGES ARISING DIRECTLY OR INDIRECTLY FROM YOUR USE OF THE SERVICES OR THE INTERNET, INCLUDING ANY INDIRECT, INCIDENTAL, EXEMPLARY, MULTIPLE, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES. IN ANY EVENT, WIFIS'S CUMULATIVE LIABILITY TO ANY USER FOR ANY AND ALL CLAIMS RELATING TO THE USE OF THE SERVICES AND/OR LICENSED PROGRAMS WILL NOT EXCEED THE TOTAL AMOUNT OF SERVICE FEES PAID DURING A ONE YEAR PERIOD PRECEDING THE ACCRUAL OF THE CLAIM. </p>

<h2>7. INDEMNIFICATION.</h2>
<p>You agree, at your expense, to defend and hold harmless WIFIS and its affiliates, officers, directors and employees from and against any and all costs, damages and reasonable attorneys' fees resulting from any claim that your use of the Services injured or otherwise violated any right of any third party or violates any law.</p> 

<h2>8. ACCEPTABLE USE POLICY.</h2>
<p>All Users of the Services and users of the WIFIS website and/or the WIFIS software agree to and must comply with this section 8, which is WIFIS's Acceptable Use Policy (AUP), and your use of any Services, website or software provided by WIFIS constitutes your agreement to abide by the terms of this AUP. This AUP is intended to improve the use of the Internet by preventing unacceptable uses. WIFIS does not actively monitor the use of the Services under normal circumstances. Similarly WIFIS does not exercise editorial control or review over the content of any website, electronic mail transmission, newsgroup, or other material created or accessible over or through the Services. However, WIFIS may remove, block, filter, or restrict by any other means any materials that, in WIFIS's sole discretion, may be illegal, may subject WIFIS to liability or may violate this AUP. WIFIS may cooperate with legal authorities and/or third parties in the investigation of any suspected or alleged crime or civil wrong. Violation of this AUP may result in the suspension or termination of either access to the Services and/or WIFIS account or other actions as detailed below. When a User uses the Services, the third-party from whom WIFIS has obtained the right to access the applicable Hot Spot at which the Services are being used is an intended third-party beneficiary of this AUP.</p>

<p>Without limiting the foregoing, you agree not to use the Services to:</p>

<p>(i) transmit any material (by uploading, posting, email or otherwise) that is unlawful, threatening, abusive, harassing, tortious, defamatory, obscene, libelous, invasive of another's privacy, hateful or racially, ethnically or otherwise objectionable;</p>
<p>(ii) harm, or attempt to harm, minors in any way;</p>
<p>(iii) impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity; forge headers or otherwise manipulate identifiers in order to disguise the origin of any material transmitted through the Services;</p>
<p>(iv) transmit any material (by uploading, posting, email or otherwise) that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</p>
<p>(v) transmit any material (by uploading, posting, email or otherwise) that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party;</p>
<p>(vi) transmit (by uploading, posting, email or otherwise) any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation;</p>
<p>(vii) transmit any material (by uploading, posting, email or otherwise) that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</p>
<p>(viii) disrupt the normal flow of dialogue, cause a screen to "scroll" faster than other users of the Service are able to type, or otherwise act in a manner that negatively affects other users' ability to engage in real time exchanges;</p>
<p>(ix) interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service;</p>
<p>(x) intentionally or unintentionally violate any applicable local, state, national or international law, including, but not limited to, regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, including, without limitation, the New York Stock Exchange, the American Stock Exchange or the NASDAQ, and any regulations having the force of law;</p>
<p>(xi) "stalk" or otherwise harass another; or collect or store, or attempt to collect or store, personal data about third parties without their knowledge or consent;</p>
<p>(xii) resell the Services without WIFIS's authorization;</p>
<p>(xiii) use the Services for high volume data transfers, especially sustained high volume data transfers, hosting a web server, IRC server, or any other server.</p>

<p>WIFIS requests that anyone who believes that there is a violation of the AUP direct the information to us. If available, please provide the following information: (i) the IP address used to commit the alleged violation; (ii) the date and time of the alleged violation, including the time zone; and (iii) evidence of the alleged violation. When reporting an issue regarding unsolicited email please provide a copy of the email messages with full headers which typically provides all of the above data. Other situations will require different methods of providing the necessary information.</p>

<p>WIFIS may take any one or more of the following actions, or other actions not listed, at WIFIS's sole discretion in response to complaints: (i) issue warnings, written or oral; (ii) suspend the User's account; (iii) terminate the User's account; (iv) bill the User or user for administrative costs and/or reactivation charges, with a minimum administrative cost; or (v) bring legal action to enjoin violations and/or to collect damages, if any, caused by violations.</p>

<h2>9. TERM OF AGREEMENT.</h2>
<p>Continued use of the Services constitutes acceptance of this Agreement and any future versions. If you are dissatisfied with the Services or any related terms, conditions, rules, policies, guidelines, or practices, your sole and exclusive remedy is to discontinue using the Services and terminate your account.</p>

<h2>10. COPYRIGHTS AND TRADEMARKS.</h2>
<p>All content included on WIFIS's website, including, but not limited to, text, graphics, logos, buttons, icons, images and software, is the property of WIFIS or its licensors or partners. Reproduction, duplication, modification, distribution, transmission, replication, display or performance of the content of the WIFIS website without the express written permission of WIFIS is strictly prohibited.</p>

<h2>11. TERMINATION OF A SUBSCRIPTION.</h2>
<p>You may terminate your account at any time and for any reason by providing notice of intent to terminate to WIFIS at least 5 business days prior to the end of your billing cycle. Your termination will only be complete upon your receipt of a cancellation confirmation number from WIFIS. If a termination notice is received at least 5 business days prior to the end of your current billing cycle, termination of your account will be effective at the end of your then current billing cycle. If a termination notice is received less than 5 business days prior to the end of your current billing cycle, charges to your account may continue until the end of the following billing cycle.</p>

<p>Without prior notice, WIFIS may terminate this Agreement, your password, your account, or your use of the Services, for any reason, including, without limitation, if WIFIS, in its sole discretion, believes you have violated this Agreement or any of the policies applicable to Users, or if you fail to pay any charges when due. WIFIS may provide termination notice to you by email or by US Mail or courier service to the address you provided for the Services. All notices to you will be deemed effective on the first (1st) calendar day following the date of electronic mailing or on the fourth (4th) calendar day following the date of first-class mailing or deposit with a commercial courier service.</p>

<p>The provisions of the following sections of this Agreement will survive termination of this Agreement 3, 5, 6, 7, 8, 10 and 11.</p>